project_id = "sktxyflbvfhxkaeaebnr"

[functions.import-houzz]
verify_jwt = false

[functions.send-quote-confirmation]
verify_jwt = false

[functions.carin-ia]
verify_jwt = false

[functions.send-prospect-followup]
verify_jwt = false

[functions.scrape-planizia]
verify_jwt = false

[functions.send-lead-confirmation]
verify_jwt = false
